version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - user-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:8
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: userdetails_db
      MYSQL_USER: sree
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - user-network
    volumes:
      - mysql-persist-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - user-network
    volumes:
      - redis-persist-data:/data
    command: redis-server --appendonly yes

volumes:
  mysql-persist-data:
  redis-persist-data:

networks:
  user-network:
    driver: bridge

